name: Product/Feature Request
description: Create a Feature Proposal for MyMeta
labels: Roadmap
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Submitted By (your name/org)
    validations:
      required: true
      
  - type: textarea
    id: feature
    attributes:
      label: Give a quick summary of the feature idea.
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why should we build this?
      This is a breakdown of why you believe MetaGame should spend time and resources to build this idea. Will it be useful for many organizations? Will it help spread the word of using MyMeta as the profile page for orgs? Will it make MyMeta more accessible/understandable to others?
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Skills Needed?
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Funding (in USD)
      Are you or your org willing to build or fund this? If so please tell how much can you contribute in it. Otherwise, leave it empty, an engaged Octo might want to take ownership of it :)
    validations:
      required: true
